modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
[[mods]] #mandatory
modId="searchablechests" #mandatory
version="1.14-1.5.3" #mandatory
displayName="Searchable Chests" #mandatory
authors="Zuve" #optional
description='''
Allows for the searching of chests similar to inventory search in creative mode.
'''